/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//Author: David Hellwig
package edu.isu.cs2263.hw01;


import org.apache.commons.cli.*;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import java.util.Arrays;

public class App {






    //Setting up the parser and options in main
    //The currently best know way (by contributor David) is to do this
    public static void main(String[] args) {
        Options options = new Options();

        options.addOption("h", "help",false,"displays help message");

        options.addOption("b","batch",true , "processes a file provided");

        options.addOption("o","output",true,"sends the output to the provided file");

        CommandLineParser parser = new DefaultParser();
        try{
            CommandLine cmd = parser.parse(options, args);

            if(cmd.hasOption("h")) {
                System.out.println("usage: eval [OPTIONS]\nEvaluation of simple mathematical expressions\n" +
                        "-b,--batch <file>    batch file containing expressions to evaluate\n" +
                        "-h,--help            print usage message\n" +
                        "-o,--output <file>   output file\n" +
                        "\t\tCopyright (C) 2021 Isaac D. Griffith"
                );
                System.exit(0);
            }
            else if (cmd.hasOption("b")){
                File batchFile = new File(Arrays.toString(cmd.getArgs())); //Fix this
                String batch = Arrays.toString(cmd.getArgs());
                System.out.println("Batch value: ".concat(batch));


            }
            else if (cmd.hasOption("o")){
                File outputFile = new File(Arrays.toString(cmd.getArgs()));// Fix it!!
                String output = Arrays.toString(cmd.getArgs());
                System.out.println("output value: ".concat(output));

        }



        }
        catch (ParseException e) {
            e.printStackTrace();
        }
    }






    }

